// This file is auto-generated by @hey-api/openapi-ts

import type { Options } from '@hey-api/client-fetch';
import type { DoctorFinderServiceFindDoctorsData, DoctorFinderServiceFindDoctorsResponse, DoctorFinderServiceFindDoctorsError, DoctorFinderServiceGetDoctorDetailsData, DoctorFinderServiceGetDoctorDetailsResponse, DoctorFinderServiceGetDoctorDetailsError, DoctorFinderServiceGetDoctorReviewsData, DoctorFinderServiceGetDoctorReviewsResponse, DoctorFinderServiceGetDoctorReviewsError, DoctorFinderServiceBookAppointmentData, DoctorFinderServiceBookAppointmentResponse, DoctorFinderServiceBookAppointmentError, DoctorFinderServiceGetAvailableSlotsData, DoctorFinderServiceGetAvailableSlotsResponse, DoctorFinderServiceGetAvailableSlotsError, DoctorFinderServiceSubmitDoctorReviewData, DoctorFinderServiceSubmitDoctorReviewResponse, DoctorFinderServiceSubmitDoctorReviewError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

/**
 * Doctor Finder Service Find Doctors
 * Main endpoint for finding doctors based on natural language query.
 * Returns ranked list of doctors with match explanations.
 */
export const doctorFinderServiceFindDoctors = <ThrowOnError extends boolean = false>(options: Options<DoctorFinderServiceFindDoctorsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DoctorFinderServiceFindDoctorsResponse, DoctorFinderServiceFindDoctorsError, ThrowOnError>({
        url: '/api/doctor_finder_service/find_doctors',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Doctor Finder Service Get Doctor Details
 * Get comprehensive details for a specific doctor.
 */
export const doctorFinderServiceGetDoctorDetails = <ThrowOnError extends boolean = false>(options: Options<DoctorFinderServiceGetDoctorDetailsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DoctorFinderServiceGetDoctorDetailsResponse, DoctorFinderServiceGetDoctorDetailsError, ThrowOnError>({
        url: '/api/doctor_finder_service/get_doctor_details',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Doctor Finder Service Get Doctor Reviews
 * Get patient reviews for a specific doctor.
 */
export const doctorFinderServiceGetDoctorReviews = <ThrowOnError extends boolean = false>(options: Options<DoctorFinderServiceGetDoctorReviewsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DoctorFinderServiceGetDoctorReviewsResponse, DoctorFinderServiceGetDoctorReviewsError, ThrowOnError>({
        url: '/api/doctor_finder_service/get_doctor_reviews',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Doctor Finder Service Book Appointment
 * Book an appointment with a doctor.
 */
export const doctorFinderServiceBookAppointment = <ThrowOnError extends boolean = false>(options: Options<DoctorFinderServiceBookAppointmentData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DoctorFinderServiceBookAppointmentResponse, DoctorFinderServiceBookAppointmentError, ThrowOnError>({
        url: '/api/doctor_finder_service/book_appointment',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Doctor Finder Service Get Available Slots
 * Get available appointment slots for a doctor within a date range.
 * This is a simplified version - real implementation would integrate with doctor&#39;s calendar system.
 */
export const doctorFinderServiceGetAvailableSlots = <ThrowOnError extends boolean = false>(options: Options<DoctorFinderServiceGetAvailableSlotsData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DoctorFinderServiceGetAvailableSlotsResponse, DoctorFinderServiceGetAvailableSlotsError, ThrowOnError>({
        url: '/api/doctor_finder_service/get_available_slots',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Doctor Finder Service Submit Doctor Review
 * Submit a review for a doctor.
 */
export const doctorFinderServiceSubmitDoctorReview = <ThrowOnError extends boolean = false>(options: Options<DoctorFinderServiceSubmitDoctorReviewData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).post<DoctorFinderServiceSubmitDoctorReviewResponse, DoctorFinderServiceSubmitDoctorReviewError, ThrowOnError>({
        url: '/api/doctor_finder_service/submit_doctor_review',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};