// This file is auto-generated by @hey-api/openapi-ts

export type Appointment = {
    id?: string;
    doctor_id: string;
    patient_name: string;
    patient_email: string;
    patient_phone: string;
    appointment_datetime: string;
    duration_minutes?: number;
    appointment_type: string;
    visit_type?: string;
    chief_complaint: string;
    symptoms_description?: string | null;
    insurance_provider?: string | null;
    insurance_plan?: string | null;
    insurance_id?: string | null;
    status?: string;
    confirmation_sent?: boolean;
    reminder_sent?: boolean;
    check_in_time?: string | null;
    check_out_time?: string | null;
    visit_notes?: string | null;
    follow_up_required?: boolean;
    follow_up_in_days?: number | null;
    estimated_cost?: number | null;
    copay_amount?: number | null;
    payment_status?: string;
    cancelled_at?: string | null;
    cancellation_reason?: string | null;
    cancelled_by?: string | null;
    created_at?: string;
    last_updated?: string;
    source_query_id?: string | null;
};

export type BodyDoctorFinderServiceBookAppointment = {
    doctor_id: string;
    patient_name: string;
    patient_email: string;
    patient_phone: string;
    appointment_datetime: string;
    chief_complaint: string;
    appointment_type: string;
    visit_type: string;
    insurance_provider?: string | null;
    insurance_plan?: string | null;
    source_query_id?: string | null;
};

export type BodyDoctorFinderServiceFindDoctors = {
    query: string;
    user_location?: string | null;
    user_latitude?: number | null;
    user_longitude?: number | null;
    max_distance_miles: number;
    insurance_provider?: string | null;
};

export type BodyDoctorFinderServiceGetAvailableSlots = {
    doctor_id: string;
    start_date: string;
    end_date: string;
};

export type BodyDoctorFinderServiceGetDoctorDetails = {
    doctor_id: string;
};

export type BodyDoctorFinderServiceGetDoctorReviews = {
    doctor_id: string;
    limit: number;
};

export type BodyDoctorFinderServiceSubmitDoctorReview = {
    doctor_id: string;
    appointment_id?: string | null;
    overall_rating: number;
    review_text?: string | null;
    patient_name?: string | null;
    condition_treated?: string | null;
    would_recommend: boolean;
};

export type Doctor = {
    id?: string;
    name: string;
    email: string;
    phone: string;
    medical_license_number: string;
    specialties: Array<string>;
    subspecialties?: Array<string> | null;
    board_certifications: Array<string>;
    medical_school: string;
    residency?: string | null;
    fellowships?: Array<string> | null;
    years_in_practice: number;
    practice_name: string;
    practice_address: string;
    practice_city: string;
    practice_state: string;
    practice_zip: string;
    practice_latitude: number;
    practice_longitude: number;
    office_hours: {
        [key: string]: unknown;
    };
    languages_spoken: Array<string>;
    conditions_treated: Array<string>;
    procedures_performed?: Array<string> | null;
    hospital_affiliations?: Array<string> | null;
    insurance_networks: Array<string>;
    overall_rating?: number | null;
    total_reviews?: number | null;
    telehealth_available?: boolean;
    new_patient_accepting?: boolean;
    next_available_appointment?: string | null;
    average_wait_time_days?: number | null;
    credentials_verified?: boolean;
    license_active?: boolean;
    last_credential_check?: string;
    created_at?: string;
    last_updated?: string;
    is_active?: boolean;
};

export type DoctorReview = {
    id?: string;
    doctor_id: string;
    appointment_id?: string | null;
    patient_name?: string | null;
    patient_email?: string | null;
    verified_patient?: boolean;
    overall_rating: number;
    communication_rating?: number | null;
    bedside_manner_rating?: number | null;
    wait_time_rating?: number | null;
    office_staff_rating?: number | null;
    review_title?: string | null;
    review_text?: string | null;
    condition_treated?: string | null;
    visit_type?: string | null;
    wait_time_minutes?: number | null;
    appointment_on_time?: boolean | null;
    would_recommend?: boolean;
    helpful_votes?: number;
    total_votes?: number;
    flagged_inappropriate?: boolean;
    moderator_approved?: boolean;
    created_at?: string;
    last_updated?: string;
    is_active?: boolean;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type DoctorFinderServiceFindDoctorsData = {
    body: BodyDoctorFinderServiceFindDoctors;
    path?: never;
    query?: never;
    url: '/api/doctor_finder_service/find_doctors';
};

export type DoctorFinderServiceFindDoctorsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DoctorFinderServiceFindDoctorsError = DoctorFinderServiceFindDoctorsErrors[keyof DoctorFinderServiceFindDoctorsErrors];

export type DoctorFinderServiceFindDoctorsResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DoctorFinderServiceFindDoctorsResponse = DoctorFinderServiceFindDoctorsResponses[keyof DoctorFinderServiceFindDoctorsResponses];

export type DoctorFinderServiceGetDoctorDetailsData = {
    body: BodyDoctorFinderServiceGetDoctorDetails;
    path?: never;
    query?: never;
    url: '/api/doctor_finder_service/get_doctor_details';
};

export type DoctorFinderServiceGetDoctorDetailsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DoctorFinderServiceGetDoctorDetailsError = DoctorFinderServiceGetDoctorDetailsErrors[keyof DoctorFinderServiceGetDoctorDetailsErrors];

export type DoctorFinderServiceGetDoctorDetailsResponses = {
    /**
     * Successful Response
     */
    200: Doctor;
};

export type DoctorFinderServiceGetDoctorDetailsResponse = DoctorFinderServiceGetDoctorDetailsResponses[keyof DoctorFinderServiceGetDoctorDetailsResponses];

export type DoctorFinderServiceGetDoctorReviewsData = {
    body: BodyDoctorFinderServiceGetDoctorReviews;
    path?: never;
    query?: never;
    url: '/api/doctor_finder_service/get_doctor_reviews';
};

export type DoctorFinderServiceGetDoctorReviewsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DoctorFinderServiceGetDoctorReviewsError = DoctorFinderServiceGetDoctorReviewsErrors[keyof DoctorFinderServiceGetDoctorReviewsErrors];

export type DoctorFinderServiceGetDoctorReviewsResponses = {
    /**
     * Successful Response
     */
    200: Array<DoctorReview>;
};

export type DoctorFinderServiceGetDoctorReviewsResponse = DoctorFinderServiceGetDoctorReviewsResponses[keyof DoctorFinderServiceGetDoctorReviewsResponses];

export type DoctorFinderServiceBookAppointmentData = {
    body: BodyDoctorFinderServiceBookAppointment;
    path?: never;
    query?: never;
    url: '/api/doctor_finder_service/book_appointment';
};

export type DoctorFinderServiceBookAppointmentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DoctorFinderServiceBookAppointmentError = DoctorFinderServiceBookAppointmentErrors[keyof DoctorFinderServiceBookAppointmentErrors];

export type DoctorFinderServiceBookAppointmentResponses = {
    /**
     * Successful Response
     */
    200: Appointment;
};

export type DoctorFinderServiceBookAppointmentResponse = DoctorFinderServiceBookAppointmentResponses[keyof DoctorFinderServiceBookAppointmentResponses];

export type DoctorFinderServiceGetAvailableSlotsData = {
    body: BodyDoctorFinderServiceGetAvailableSlots;
    path?: never;
    query?: never;
    url: '/api/doctor_finder_service/get_available_slots';
};

export type DoctorFinderServiceGetAvailableSlotsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DoctorFinderServiceGetAvailableSlotsError = DoctorFinderServiceGetAvailableSlotsErrors[keyof DoctorFinderServiceGetAvailableSlotsErrors];

export type DoctorFinderServiceGetAvailableSlotsResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type DoctorFinderServiceGetAvailableSlotsResponse = DoctorFinderServiceGetAvailableSlotsResponses[keyof DoctorFinderServiceGetAvailableSlotsResponses];

export type DoctorFinderServiceSubmitDoctorReviewData = {
    body: BodyDoctorFinderServiceSubmitDoctorReview;
    path?: never;
    query?: never;
    url: '/api/doctor_finder_service/submit_doctor_review';
};

export type DoctorFinderServiceSubmitDoctorReviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DoctorFinderServiceSubmitDoctorReviewError = DoctorFinderServiceSubmitDoctorReviewErrors[keyof DoctorFinderServiceSubmitDoctorReviewErrors];

export type DoctorFinderServiceSubmitDoctorReviewResponses = {
    /**
     * Successful Response
     */
    200: DoctorReview;
};

export type DoctorFinderServiceSubmitDoctorReviewResponse = DoctorFinderServiceSubmitDoctorReviewResponses[keyof DoctorFinderServiceSubmitDoctorReviewResponses];